# Generated by Django 3.2 on 2021-04-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(blank=True, max_length=250, null=True)),
                ('movie_rating', models.CharField(blank=True, max_length=250, null=True)),
                ('movie_release_date', models.CharField(blank=True, max_length=250, null=True)),
                ('movie_duration', models.CharField(blank=True, max_length=250, null=True)),
                ('movie_descriptions', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
    ]
