# Generated by Django 3.2 on 2021-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='movie_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
