# Generated by Django 3.2 on 2021-04-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_details_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='movie_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
